name: yam
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  splash_screen_view: ^3.0.0
  flutter:
    sdk: flutter
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_analytics: ^8.3.3
  cloud_firestore: ^2.5.3
  clay_containers:
  syncfusion_flutter_charts: ^19.1.54
  http: ^0.13.4
  firebase_database: ^9.0.5
  url_launcher:
  launch_review:
  store_launcher:
  syncfusion_flutter_gauges:
  curved_navigation_bar: ^1.0.1
  flutter_local_notifications: ^9.2.0
  rxdart: ^0.27.3
  firebase_messaging: ^11.2.5


  #splashscreen:
  #flutter_native_splash:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  build_runner:


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - yamLogo2.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  #color: "#ffffff"
  #background_image: "assets/yamLogo2.png"

  #
  image: yamLogo2.png

